version: "3.8"

services:
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    volumes:
      - "mongo1_data:/data/db"

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27018:27017
    volumes:
      - "mongo2_data:/data/db"

  mongo3:
    image: mongo:7.0
    container_name: mongo3
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27019:27017
    volumes:
      - "mongo3_data:/data/db"

  mongo-initiate:
    image: mongo:7.0
    container_name: mongo_initiate
    depends_on:
      mongo1:
        condition: service_started
      mongo2:
        condition: service_started
      mongo3:
        condition: service_started
    entrypoint: [ "/bin/bash", "-c" ]
    command: |
      "
      echo 'Iniciando o Replica Set...'
      sleep 15 # Dê tempo para que todos os serviços mongo estejam prontos

      mongosh --host mongo1:27017 <<EOF
      rs.initiate({
        _id: "rs0",
        members: [
          { _id: 0, host: "mongo1:27017" },
          { _id: 1, host: "mongo2:27017" },
          { _id: 2, host: "mongo3:27017" }
        ]
      })
      EOF
      echo 'Replica Set iniciado.'
      "

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data: